services:
  - type: web
    name: cologne-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://cologne-ecommerce.netlify.app
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        value: whsec_QlLf8MYSHPBRQkCcrOLcN7A6FKW66puQ
    healthCheckPath: /
    autoDeploy: true 
